title: BrikMentionの広場
name: BrikMentionの広場
author: BrikMention
url: https://BrikMention.github.io
img_dir: /assets/img
logo: /assets/img/logo.jpg
keep_files: [assets]
sass:
  sass_dir: /assets/css/_sass
plugins:
  - jekyll-sitemap

theme: jekyll-theme-hacker
google_analytics: UA-295841008
